import { ScreenSize } from "@/components/sharedui/screenSize";
import "@/styles/globals.css";
import { Lato } from "next/font/google";

const lato = Lato({ subsets: ["latin"],weight:"400" });

export const metadata = {
  title: "EatYes!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <ScreenSize>{children}</ScreenSize>
      </body>
    </html>
  );
}
